### ISSUE TITLE
TypeError: babel.Transformer is not a function

### ISSUE THREAD

**Issue by radiovisual** [power-assert-js/babel-plugin-espower#10]
When I run this command to transpile via babel:

`babel lib --out-dir=dist`

I get the following error:

<pre>
TypeError: babel.Transformer is not a function
    at createEspowerPlugin (/Users/michael/gitprojects/mytestapp/node_modules/babel-plugin-espower/create.js:6:12)
    at module.exports (/Users/michael/gitprojects/mytestapp/node_modules/babel-plugin-espower/index.js:16:12)
    at Function.memoisePluginContainer (/Users/michael/gitprojects/mytestapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:127:13)
    at Function.normalisePlugin (/Users/michael/gitprojects/mytestapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:161:32)
    at /Users/michael/gitprojects/mytestapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:197:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/michael/gitprojects/mytestapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:173:20)
    at OptionManager.mergeOptions (/Users/michael/gitprojects/mytestapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:271:36)
    at OptionManager.addConfig (/Users/michael/gitprojects/mytestapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
    at OptionManager.findConfigs (/Users/michael/gitprojects/mytestapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:16)
</pre>

I am using the following babel packages/plugins:

<pre>
    "babel-cli": "^6.2.0",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-stage-3": "^6.1.18",
</pre>

I read [your warning](https://github.com/power-assert-js/babel-plugin-espower#caution) that Babel 5 needs to use the older release of the plugin: `babel-plugin-espower@1.1.0`, but I am using Babel 6.x in my app, but my attempt to transpile always ends in this error. 

*Any ideas?*

**Comment by twada** [comment]
@radiovisual Thank you for reporting.
To run with Babel 6, you need to install babel-plugin-espower 2.0.0 or above.

The message `babel.Transformer is not a function` indicates that [babel-plugin-espower 1.1.0 is running](https://github.com/power-assert-js/babel-plugin-espower/blob/1.0.x/create.js#L6)

Please delete `node_modules` and try `npm install --save-dev babel-plugin-espower` again.

**Comment by radiovisual** [comment]
@twada , Thanks for the quick response, I really appreciate it! 

Your suggestion worked. As soon as I re-installed the latest version and removed all traces of the old version from my `node_modules` directory the problem went away.

Thanks again! :smile:

**Comment by twada** [comment]
@radiovisual Glad to hear that! :smiley:
